baseURL = "https://docs.brigade.sh/"
title = "Brigade Docs"
theme = "techdoc-brigade"
canonifyURLs = "true"
relativeURLs = "true"

[params]
  title = "Brigade"
  description = "Brigade: Event-driven scripting for Kubernetes."

# main docs 'index' menu on left
[[menu.index]]
    name = "Home"
    url = "/"
    weight = 10
[[menu.index]]
    name = "Getting Started"
    url = "/intro/"
    weight = 20
    identifier = "intro"
    [[menu.index]]
    name = "Overview"
    url = "/intro/overview/"
    weight = 21
    parent = "intro"
    [[menu.index]]
    name = "QuickStart"
    url = "/intro/quickstart/"
    weight = 22
    parent = "intro"
    [[menu.index]]
    name = "Installing Brigade"
    url = "/intro/install/"
    weight = 23
    parent = "intro"
    [[menu.index]]
    name = "What to Read Next"
    url = "/intro/readnext/"
    weight = 29
    parent = "intro"

[[menu.index]]
    name = "Topic Guides"
    url = "/topics/"
    weight = 40
    identifier = "topics"
    [[menu.index]]
    name = "Design"
    url = "/topics/design/"
    weight = 41
    parent = "topics"
    [[menu.index]]
    name = "Scripting Guide"
    url = "/topics/scripting/"
    weight = 42
    parent = "topics"
    [[menu.index]]
    name = "The Brig CLI"
    url = "/topics/brig/"
    weight = 42
    parent = "topics"
    [[menu.index]]
    name = "The Brigade.js API"
    url = "/topics/javascript/"
    weight = 43
    parent = "topics"
    [[menu.index]]
    name = "Advanced Scripting Guide"
    url = "/topics/scripting_advanced/"
    weight = 44
    parent = "topics"
    [[menu.index]]
    name = "Dependencies"
    url = "/topics/dependencies/"
    weight = 45
    parent = "topics"
    [[menu.index]]
    name = "Secret Management"
    url = "/topics/secrets/"
    weight = 49
    parent = "topics"
    [[menu.index]]
    name = "Gateways"
    url = "/topics/gateways/"
    weight = 50
    parent = "topics"
    [[menu.index]]
    name = "Projects"
    url = "/topics/projects/"
    weight = 52
    parent = "topics"
    [[menu.index]]
    name = "Securing Brigade"
    url = "/topics/security/"
    weight = 53
    parent = "topics"
    [[menu.index]]
    name = "Workers"
    url = "/topics/workers/"
    weight = 55
    parent = "topics"
    [[menu.index]]
    name = "Testing"
    url = "/topics/testing/"
    weight = 56
    parent = "topics"
    [[menu.index]]
    name = "Developer Guide"
    url = "/topics/developers/"
    weight = 57
    parent = "topics"
[[menu.index]]
    name = "Releasing Brigade"
    url = "/releasing/"
    weight = 59
    [[menu.index]]
    name = "Contributing"
    url = "/contributing/"
    weight = 60


# top navigation - project links
[[menu.main]]
    name = "Docs"
    url = "https://docs.brigade.sh"
    weight = 1

[[menu.main]]
    name = "Examples"
    url = "https://github.com/brigadecore/brigade/tree/v2/examples"
    weight = 2

[[menu.main]]
    name = "Github"
    url = "https://github.com/brigadecore/brigade"
    weight = 3
